### ISSUE TITLE
i40e/XL710 not receiving packets

### ISSUE THREAD

**Issue by tbarbette** [ndsl-kaist/mOS-networking-stack#13]
Hi all,

I cannot receive any packets using XL710 cards.
I modified dpdk_module.c to print something if any packet is received and I've got nothing. MAC are set correctly though...
Did anyone actually achieved to use them with mOS?
Thanks,
Tom

**Comment by a-jamshed** [comment]
tbarbette,

i40e compatible devices should work fine. Can you please test mOS by first running ``epserver`` and ``epwget`` on two different nodes that are directly communicating with each other (without any middlebox)? 

If you see any issues, can you please share your ``mos.conf`` files for both client and the server?

**Comment by tbarbette** [comment]
Ok. The code source stated that parameters were tuned for ixgbe, so I thought this could be the problem. I'll look elsewhere then :p

**Comment by tbarbette** [comment]
Hi again ajamshed,
I could make epserver and epwget work and I got some packets with nat, however no packet is passing through and the NAT application is taking more and more memory until it eventually run OOM. Here is my configuration : 
```

############### MOS configuration file ###############

#######################
# MOS-RELATED OPTIONS #
#######################
mos {
	forward = 1

	#######################
	##### I/O OPTIONS #####
	#######################
	# number of memory channels per socket [mandatory for DPDK]
	nb_mem_channels = 4

	# devices used for MOS applications [mandatory]
	netdev {
		dpdk0 0x00FF
		dpdk1 0x00FF
	}

	#######################
	### LOGGING OPTIONS ###
	#######################
	# NICs to print network statistics per second
	# if enabled, mTCP will print xx Gbps and xx pps for RX and TX
	stat_print = dpdk0 dpdk1

	# A directory contains MOS system log files
	mos_log = logs/

	########################
	## NETWORK PARAMETERS ##
	########################
	# This to configure static arp table
	# (Destination IP address) (Destination MAC address)
	arp_table {
        10.220.0.1 3c:fd:fe:9e:5c:40
        10.221.0.1 3c:fd:fe:9e:5c:41
        10.220.0.5 3c:fd:fe:9e:5b:60
        10.221.0.5 3c:fd:fe:9f:57:18 
	}

	# This is to configure static routing table
	# (Destination address)/(Prefix) (Device name)
	route_table {
#        10.220.0.0/16 dpdk0
#        10.221.0.0/16 dpdk1
	}

	# This is to configure static bump-in-the-wire NIC forwarding table
	# DEVNIC_A DEVNIC_B ## (e.g. dpdk0 dpdk1) 
	nic_forward_table {	
        dpdk0 dpdk1
	}

	########################
	### ADVANCED OPTIONS ###
	########################
	# if required, uncomment the following options and change them

	# maximum concurrency per core [optional / default : 100000]
	# (MOS-specific parameter for preallocation)
	# max_concurrency = 100000

	# disable the ring buffer [optional / default : 0]
	# use disabled buffered managment only for standalone monitors.
	# end host applications always need recv buffers for TCP!
	# no_ring_buffers = 1

	# receive buffer size of sockets [optional / default : 8192]
	# rmem_size = 8192

	# send buffer size of sockets [optional / default : 8192]
	# wmem_size = 8192

	# tcp timewait seconds [optional / default : 0]
	tcp_tw_interval = 30

	# tcp timeout seconds [optional / default : 30]
	# (set tcp_timeout = -1 to disable timeout checking)
	# tcp_timeout = 30
}
```
I run with 
sudo ./nat -i 10.221.0.3

I've got one client (10.220.0.5) connected to the first port (10.220.0.1) on vlan 1 (thus there may be a little garbage traffic) and the second port (10.221.0.1 and .3) connected to (10.221.0.5) isoled together on vlan 10.

Any idea?
Thanks

**Comment by tbarbette** [comment]
Ok I got it, without -c it's taking all the cores and 100000 connections per default lead to a lot of per-thread memory, leading to the OOM.
