### ISSUE TITLE
insmod: ERROR: could not insert module drivers/dpdk-16.11/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko: Unknown symbol in module

### ISSUE THREAD

**Issue by Aoeda** [ndsl-kaist/mOS-networking-stack#15]
I can compile and build mOS net library with DPDK using command `./setup.sh --compile-dpdk`
But when I run mOS with `./setup.sh --run-dpdk` and select 2, I get unknown symbol in module error.
```
Option: 2
Unloading any existing DPDK UIO module
Loading uio module
Loading DPDK UIO module
insmod: ERROR: could not insert module drivers/dpdk-16.11/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko: Unknown symbol in module
## ERROR: Could not load kmod/igb_uio.ko.
./setup.sh: line 333: quit: command not found
# Please load the 'igb_uio' kernel module before querying or 
# adjusting NIC device bindings
```

**Comment by a-jamshed** [comment]
Please check if your OS has ``uio`` kernel module. ``igb_uio`` kernel module depends on ``uio``.

**Comment by ygmoon** [comment]
In case your OS has `uio `kernel module, please try `dmesg | grep igb_uio` and share us the result.

**Comment by Aoeda** [comment]
I solved it by using `modprobe uio`
Thank you :D

**Comment by ygmoon** [comment]
Okay, I accidently closed the issue by pressing a wrong button.. Sorry for messing things up!

**Comment by a-jamshed** [comment]
@ygmoon : we should probably update ``setup.sh`` to give an error printf if ``uio`` is not inserted in the kernel.

**Comment by ygmoon** [comment]
@ajamshed : okay, I will update this soon, thanks for the suggestion!
