### ISSUE TITLE
Problem starting midstat: EAL: Error - exiting with code: 1   Cause: Cannot init mbuf pool

### ISSUE THREAD

**Issue by eratormortimer** [ndsl-kaist/mOS-networking-stack#7]
I have a problem starting midstat. 
I set up mOS with ./setup.sh --compile-dpdk and ./setup.sh --run-dpdk
I load eth Devices 04:00.0 and 04:00.1 and give them 2 IP addresses. 
I create config files without an error. 
I change into the directory of midstat and use make, it works without an error. 
When I now try to start midstat with ./midstat I get:  
<pre>`EAL: Detected 8 lcore(s)  
EAL: Auto-detected process type: PRIMARY  
EAL: Probing VFIO support...  
EAL: PCI device 0000:04:00.0 on NUMA socket -1  
EAL:   probe driver: 8086:1526 net_e1000_igb  
EAL: PCI device 0000:04:00.1 on NUMA socket -1  
EAL:   probe driver: 8086:1526 net_e1000_igb  
EAL: PCI device 0000:06:00.0 on NUMA socket -1  
EAL:   probe driver: 8086:1526 net_e1000_igb  
EAL: PCI device 0000:06:00.1 on NUMA socket -1  
EAL:   probe driver: 8086:1526 net_e1000_igb  
EAL: PCI device 0000:09:00.0 on NUMA socket -1  
EAL:   probe driver: 8086:10d3 net_e1000_em  
load_module(): 0x8b6fc0  
EAL: Error - exiting with code: 1  
  Cause: Cannot init mbuf pool  
`</pre>
It worked 2 weeks ago so I guess something in the dependencies changed? 
I use a fresh debian-jessie on 

- CPU: Intel(R) Xeon(R) CPU E31230 @ 3.20GHz
- Number of CPUs: 1
- Memory: 16 GB
- Mainboard: X9SCL/X9SCM
- Mgmt MAC: 00:25:90:74:77:b8
- IPMI MAC: 00:25:90:74:72:cd
- NICs: 4x 82576

I install the dependencies with: 
<pre>`#!/bin/bash  
apt-get update -y  
apt-get install linux-headers-$(uname -r) -y  
apt-get install libnuma-dev -y  
apt-get install libc6 -y  
apt-get install libssl-dev -y  
apt-get install libglib2.0-0 -y  
apt-get install libdpdk-dev -y  
apt-get install pciutils -y  
`</pre>
Can you help me out? I'm a relative newbie in this so sorry if something important is missing

**Comment by a-jamshed** [comment]
The error says that the underlying dpdk library failed to create mbuf pool. This most likely means that mbuf was unable to access huge pages that are needed by dpdk applications. Can you please check the following things:

1- Check if you are running with `sudo` privileges.
2- Check if huge pages have actually been reserved by dpdk. There are multiple ways to check it. One method is to run ``cat /proc/meminfo`` and check if huge pages have already been reserved by your OS.
3- See if you can run any sample dpdk applications that are present in ``drivers/dpdk-16.11/examples/`` directory. Since this is a common ``dpdk`` issue, this will help identify the root cause of the problem more quickly.

**Comment by eratormortimer** [comment]
Hey thanks for the fast answer.  
1. I ran everything with sudo.  
2.  `cat /proc/meminfo` gives me as output:  
<pre>`MemTotal:       16441752 kB  
MemFree:        14788576 kB  
MemAvailable:   15357908 kB  
Buffers:           85336 kB  
Cached:          1195876 kB  
SwapCached:            0 kB  
Active:           616096 kB  
Inactive:         693344 kB  
Active(anon):     335676 kB  
Inactive(anon):   292624 kB  
Active(file):     280420 kB  
Inactive(file):   400720 kB  
Unevictable:           0 kB  
Mlocked:               0 kB  
SwapTotal:             0 kB  
SwapFree:              0 kB  
Dirty:                 0 kB  
Writeback:             0 kB  
AnonPages:         28500 kB  
Mapped:            30580 kB  
Shmem:            599816 kB  
Slab:             158060 kB  
SReclaimable:     114272 kB  
SUnreclaim:        43788 kB  
KernelStack:        2000 kB  
PageTables:         4516 kB  
NFS_Unstable:          0 kB  
Bounce:                0 kB  
WritebackTmp:          0 kB  
CommitLimit:     8155340 kB  
Committed_AS:     652088 kB  
VmallocTotal:   34359738367 kB  
VmallocUsed:      102180 kB  
VmallocChunk:   34359627772 kB  
HardwareCorrupted:     0 kB  
AnonHugePages:         0 kB  
HugePages_Total:      64  
HugePages_Free:        0  
HugePages_Rsvd:        0  
HugePages_Surp:        0  
Hugepagesize:       2048 kB  
DirectMap4k:       83256 kB  
DirectMap2M:    16666624 kB  
`</pre>
I asume hugePages worked since they seem to be reserved. I chose 64 for the hugepages.  
3.  I ran 3 example applications in `drivers/dpdk-16.11/examples`:   

- cmdline
- l2fwd
- l3fwd  
For all of them I used  
`export RTE_SDK=/root/mOS-networking-stack-master/drivers/dpdk-16.11 `  
and `export RTE_TARGET=x86_64-native-linuxapp-gcc`  
as mOS used in the setup script. 
I executed `make` for all 3 and it worked. I could start cmdline and l2fwd without problems, l3fwd throws this error however when I try to execute it with the example parameters from the dpdk page:  
<pre>`./build/l3fwd -l 1,2 -n 4 -- -p 0x3 --config="(0,0,1),(1,0,2)"  
EAL: Detected 8 lcore(s)  
EAL: Probing VFIO support...  
EAL: PCI device 0000:02:00.0 on NUMA socket -1  
EAL:   probe driver: 8086:10c9 net_e1000_igb  
EAL: PCI device 0000:02:00.1 on NUMA socket -1  
EAL:   probe driver: 8086:10c9 net_e1000_igb  
EAL: PCI device 0000:05:00.0 on NUMA socket -1  
EAL:   probe driver: 8086:10d3 net_e1000_em  
L3FWD: LPM or EM none selected, default LPM on  
port 1 is not present on the board  
EAL: Error - exiting with code: 1  
  Cause: check_port_config failed  
`</pre>

**Comment by a-jamshed** [comment]
Hi eratormortimer,

I just tested this setup on my testbed. It seems to be working fine (although I was using Intel 82599/X520 adapters). I see from your dependencies list that you installed ``libdpdk-dev`` library from your Linux distribution as well. When you first successfully tested mOS 2 weeks ago, did you have the same library installed over there as well? I suspect that due to a version mismatch between ``libdpdk-dev`` and dpdk-16.11-mOS, you are facing this issue.

There is an easy way to check this idea. Please uninstall ``libdpdk-dev`` from your system, setup mOS and rerun midstat.

**Comment by eratormortimer** [comment]
Sadly that didn't help.  
I used the same setup only without `libdpdk-dev`  
I still get the same error when I try to start midstat.  
The setup worked 2 weeks ago with `libdpdk-dev` although I am not sure if I really needed it.  
My idea was as well that some dependency updated recently and that causes the problem. I don't really know however how to check this. I tried the same process on `ubuntu-16.04` and I still get the same error.

**Comment by a-jamshed** [comment]
That is very weird. Let me do some tests and I will get back to you when I find the answer.

**Comment by eratormortimer** [comment]
Update: I solved the problem. I had not enough hugepages. With 2048 hugepages it now works. Thanks for the help :)

**Comment by a-jamshed** [comment]
I am glad the issue got resolved.
