### ISSUE TITLE
Issue with running sample application using > 2 cores.

### ISSUE THREAD

**Issue by koolzz** [ndsl-kaist/mOS-networking-stack#8]
Hi, I'm trying to run sample epserver with 8 cores but it stops working without an error message. At times it prints the first stat print dump but stops after that. When only given 2 cores the sample epserver works perfectly fine. I'm also succesfull at running epwget with 8 cores. 

Moreover, I'm able to run the mtcp epserver (https://github.com/eunyoung14/mtcp) on the same machine with any number of cores without an issue. But when using it I received a large number of HANDLE_TCP_ST_CLOSING:1133  NOT ACK errors when testing it with large number of total_flows in epwget. But the mOS sample epserver running with 2 cores doesn't give me that error with the same test run. 

![image](https://user-images.githubusercontent.com/11281728/27006386-ee960868-4e00-11e7-923a-35cf47a5f343.png)  

Running it with gdb I can see the new thread creation messages and then all of them simply exit.

![image](https://user-images.githubusercontent.com/11281728/27006497-fde87fd8-4e02-11e7-85f1-77652e862aa9.png)  
   
I was hoping you can help me figure this out. Which information do you need from me? I was using the generated mos config and following the standard install instructions for dpdk setup from here http://mos.kaist.edu/guide/walkthrough/03_setup.html#compile-and-build-mos-net-library-with-dpdk

Sincerely, Nick

**Comment by a-jamshed** [comment]
Hi,

Can you please check your dmesg log? It looks like you may be facing OOM (out of memory) issues. How much RAM does your system have? You can try reducing mOS stack's memory fingerprint by reducing the ``max_concurrency`` limit to a lower value.

**Comment by kyoungsoo** [comment]
Hi Asim,

You are talking about OOM of kernel. Well, I think it is better to warn the
user if it allocates too much memory at start out of all physical memory.
That way, the user could develop a better idea why it crashes.

--KyoungSoo

2017년 6월 11일 (일) 오전 8:03, Asim Jamshed <notifications@github.com>님이 작성:

**Comment by koolzz** [comment]
@ajamshed 
Thanks for the quick response, this was exactly the cause of my issue. I'm running 16 GB or ram, after reducing the max_concurrency to 10000 everything works.
